package org.dianaframework.swing.model;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import org.dianaframework.view.BusinessObjectsCollection;
import org.dianaframework.view.CollectionModel;

/**
 *
 * Abstract list model for br.ufjf.caed.exemplo.model.NiveisTesteCombo objects;
 * Generated by Diana Framework. DO NOT EDIT!!!
 *
 */
public class EmptyListModel extends AbstractListModel implements ComboBoxModel, CollectionModel {
private List<Object[]> objects;
private Object[] selected;
private BusinessObjectsCollection boc;
private JComponent list;

    public EmptyListModel() {
        objects = new ArrayList();
    }

    public void setSelectedItem(int item) {
        if (objects != null && objects.size() > 0) {
            selected = objects.get(item);
        } else {
            selected = null;
        }
    }
    
    public void setSelectedItem(Object item) {
        if ( objects != null ) {
            for (int inc = 0; inc < objects.size(); inc++) {
                if (item != null && objects.get(inc)[0].equals(item)) {
                    selected = objects.get(inc);
                    break;
                }
            }
        }
    }

    public Object getSelectedItem() {
        return selected == null ? "" : selected[0];
    }

    public Object getElementAt(int ind) {
        return objects.get(ind)[0];
    }

    public int getSize() {
        if (objects == null) {
            return 0;
        } else {
            return objects.size();
        }
    }

    public void setBusinessObjectsCollection(BusinessObjectsCollection boc) {
        this.boc = boc;
    }

    public void setObjectsCollection(List objects) {
        // @todo 29012007: Item selecionado no combo box
        this.objects = objects;
        if (objects != null && objects.size() > 0) {
            selected = (Object[])objects.get(0);
            setSelectedIndex(0);
        } else {
            selected = null;
        }
        if (list != null) {
            ((JComponent)list).updateUI();
        }
    }

    public List getObjects() {
        return objects;
    }

    public void reload() {
        objects = boc.collection();
    }

    public Object getSelectedObject() {
        return selected[1];
    }

    public String getSelectedValue() {
        return selected == null ? "" : (String)selected[0];
    }

    public Object getObjectAt(int index){
        return objects.get(index);
    }

    public void setObjects(List<Object[]> val) {
        this.objects = val;
    }

    public Object[] getSelected() {
        return selected;
    }

    public void addObject(Object obj) {
    }

    public void removeAll() {
        objects.clear();
    }

    public Object removeObject(int index) {
        return null;
    }

    public Object removeObject(Object obj) {
        return null;
    }

    public Object removeSelectedObject() {
        return null;
    }

    public void setSelectedObject(Object obj) {
        // @todo 02022007: O problema aqui e q num EmptyListModel objects sempre e nulo e nao consigo selecionar ninguem
        if ( objects != null ) {
            for (int inc = 0; inc < objects.size(); inc++) {
                if (obj != null && objects.get(inc)[1] != null && objects.get(inc)[1].equals(obj)) {
                    selected = objects.get(inc);
                    break;
                }
            }
        }
    }

    public void setSelected(Object[] val) {
        this.selected = val;
    }

    public BusinessObjectsCollection getBoc() {
        return boc;
    }

    public void setBoc(BusinessObjectsCollection val) {
        this.boc = val;
    }

    public void setUIReference(Object ui) {
        list = (JComponent)ui;
    }

    public JComponent getUIReference() {
        return list;
    }
    
    public List getSelectedObjects() {
        return null;
    }

    public void setColumnsOrder(int[] columnsOrder) {
    }

    private void setSelectedIndex(int item) {
        if (list instanceof JComboBox) {
            ActionListener[] al = ((JComboBox)list).getActionListeners();
            // Removing all listeners before set the selected index
            for (int inc = 0; inc < al.length; inc++)
                ((JComboBox)list).removeActionListener(al[inc]);
            ((JComboBox)list).setSelectedIndex(item);
            // Put again all listeners after set the selected index
            for (int inc = 0; inc < al.length; inc++)
                ((JComboBox)list).addActionListener(al[inc]);
        }
    }

    public void setParameters(HashMap<String, String> parameters) {
    
    }
    
    public HashMap<String, String> getParameters() {
        return null;
    }

    public void addParameter(String name, String value) {
    
    }

    public void sortByColumn(int column, boolean isAscent) {}

}
