package org.dianaframework.swing.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import org.dianaframework.view.BusinessObjectsCollection;
import org.dianaframework.view.CollectionModel;

/**
 *
 * Abstract table model for br.ufjf.caed.exemplo.model.ColecaoNoticias objects;
 * Generated by Diana Framework. DO NOT EDIT!!!
 *
 */
public class EmptyTableModel extends AbstractTableModel implements CollectionModel {
private List objects;
private BusinessObjectsCollection boc;
private Object selectedObject;
private JTable jtable;

    public EmptyTableModel() {
    }

    public void setSelectedItem(int item) {
    }

    public EmptyTableModel(List objects) {
        this.objects = objects;
    }

    public void setObjects(ArrayList val) {
        this.objects = val;
    }
    public String getColumnName(int col) {
        switch (col) {
            case 0: return "Titulo";

            default: return "";
        }
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        Object object = objects.get(rowIndex);
        if (object != null) {
            switch (columnIndex) {
            case 0: return "";

            }
        }
        return null;
    }

    public int getRowCount() {
        if (objects != null) {
            return this.objects.size();
        }
        return 0;
    }

    public int getColumnCount() {
        return 1;

    }
    public Object getObjectAt(int row) {
        if (row >= 0) {
            return this.objects.get(row);
        }
        return null;
    }

    public void setBusinessObjectsCollection(BusinessObjectsCollection boc) {
        this.boc = boc;
    }

    public List getObjects() {
        return objects;
    }

    public void reload() {
        objects = boc.collection();
    }

    public void setObjectsCollection(List objects) {
        this.objects = objects;
    }

    public String getSelectedValue() {
        return "";
    }
    public Object getSelectedObject() {
        return selectedObject;
    }

    public void setSelectedObject(Object selectedObject) {
        this.selectedObject = selectedObject;
    }

    public void addObject(Object obj) {
        objects.add(obj);
    }

    public void removeAll() {
        objects.clear();
    }

    public Object removeObject(int index) {
        return objects.remove(index);
    }

    public Object removeObject(Object obj) {
        return null;
    }

    public Object removeObject(String value) {
        return null;
    }

    public Object removeSelectedObject() {
        return objects.remove(selectedObject);
    }

    public BusinessObjectsCollection getBoc() {
        return boc;
    }

    public void setBoc(BusinessObjectsCollection val) {
        this.boc = val;
    }

    public void setUIReference(Object ui) {
        jtable = (JTable)ui;
    }

    public JTable getUIReference() {
        return jtable;
    }
    
    public List getSelectedObjects() {
        return null;
    }

    public void setColumnsOrder(int[] columnsOrder) {
    }

    public void setParameters(HashMap<String, String> parameters) {
    
    }
    
    public HashMap<String, String> getParameters() {
        return null;
    }

    public void addParameter(String name, String value) {
    
    }

    public void sortByColumn(int column, boolean isAscent) {}

}
